openapi: 3.0.0
servers:
  - url: https://disease.sh
externalDocs:
  description: Find out more about this API
  url: https://github.com/disease-sh/API
info:
  description: Third Party API for reliable global disease information
  license:
    name: GNU V3
    url: https://github.com/disease-sh/API/blob/master/LICENSE
  title: disease.sh Docs - An open API for disease-related statistics
  version: 3.0.0-oas3



paths:
  /v3/covid-19/all:
    get:
      parameters:
      - description: a day ago
        in: query
        name: yesterday
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
      - description: two days ago
        in: query
        name: twoDaysAgo
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
      
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/covidAll'
          description: Status OK
      summary: Get global COVID-19 totals
      tags:
      - 'COVID-19: Worldometers'
 
  /v3/covid-19/continents:
    get:
      parameters:
      - description: a day ago
        in: query
        name: yesterday
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
      - description: two days ago
        in: query
        name: twoDaysAgo
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
      - description: field to sort
        in: query
        name: sort
        schema:
          enum:
          - cases
          - todayCases
          - deaths
          - todayDeaths
          - recovered
          - active
          - critical
          - casesPerOneMillion
          - deathsPerOneMillion
          type: string
   
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/covidContinents'
          description: Status OK
      summary: Get COVID-19 totals for all continents
      tags:
      - 'COVID-19: Worldometers'
  /v3/covid-19/continents/{continent}:
    get:
      parameters:
      - description: Continent name
        in: path
        name: continent
        required: true
        schema:
          type: string
      - description: a day ago
        in: query
        name: yesterday
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
      - description: two days ago
        in: query
        name: twoDaysAgo
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
      - description: fuzzy search
        in: query
        name: strict
        schema:
          default: 'true'
          enum:
          - 'true'
          - 'false'
          type: string
     
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/covidContinent'
          description: Status OK
      summary: Get COVID-19 totals for a specific continent
      tags:
      - 'COVID-19: Worldometers'
  /v3/covid-19/countries:
    get:
      parameters:
      - description:  a day ago
        in: query
        name: yesterday
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
      - description:  two days ago
        in: query
        name: twoDaysAgo
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
      - description: Field to sort
        in: query
        name: sort
        schema:
          enum:
          - cases
          - todayCases
          - deaths
          - todayDeaths
          - recovered
          - active
          - critical
          - casesPerOneMillion
          - deathsPerOneMillion
          type: string
      - description: allow nulls
        in: query
        name: allowNull
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/covidCountries'
          description: Status OK
      summary: Get COVID-19 totals for all countries
      tags:
      - 'COVID-19: Worldometers'
  /v3/covid-19/countries/{countries}:
    get:
      parameters:
      - description: Multiple countries separated by comma
        in: path
        name: countries
        required: true
        schema:
          type: string
      - description: a day ago
        in: query
        name: yesterday
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
      - description: two days ago
        in: query
        name: twoDaysAgo
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
      - description: allow null
        in: query
        name: allowNull
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/covidCountries'
          description: Status OK
      summary: Get COVID-19 totals for a specific set of countries
      tags:
      - 'COVID-19: Worldometers'
  /v3/covid-19/countries/{country}:
    get:
      parameters:
      - description: country code
        in: path
        name: country
        required: true
        schema:
          type: string
      - description: a day ago
        in: query
        name: yesterday
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
      - description: two days ago
        in: query
        name: twoDaysAgo
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
      - description: fuzzy search
        in: query
        name: strict
        schema:
          default: 'true'
          enum:
          - 'true'
          - 'false'
          type: string
      
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/covidCountry'
          description: Status OK
      summary: Get COVID-19 totals for a specific country
      tags:
      - 'COVID-19: Worldometers'
  
  
  /v3/covid-19/states:
    get:
      parameters:
      - description: fields to sort
        in: query
        name: sort
        schema:
          enum:
          - cases
          - todayCases
          - deaths
          - todayDeaths
          - active
          type: string
      - description: a day ago
        in: query
        name: yesterday
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
     
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/covidStates'
          description: Status OK
      summary: Get COVID-19 totals for all US States
      tags:
      - 'COVID-19: Worldometers'
  /v3/covid-19/states/{states}:
    get:
      parameters:
      - description: State name or comma separated names 
        in: path
        name: states
        required: true
        schema:
          type: string
      - description: a day ago
        in: query
        name: yesterday
        schema:
          enum:
          - 'true'
          - 'false'
          - '1'
          - '0'
          type: string
    
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/covidState'
          description: Status OK
      summary: Get COVID-19 totals for specific US State(s)
      tags:
      - 'COVID-19: Worldometers'
  
  /v3/covid-19/vaccine:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vaccines'
          description: Status Ok
      summary: Get vaccine trial data from RAPS
      tags:
      - 'COVID-19: Vaccine'
  /v3/covid-19/vaccine/coverage:
    get:
      parameters:
      - description: Number of days 
        in: query
        name: lastdays
        schema:
          default: 30
          type: string
      - description: simple or full
        in: query
        name: fullData
        schema:
          default: 'false'
          type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                fullTimeline:
                  $ref: '#/components/examples/fullVaccineTimeline'
                simpleTimeline:
                  $ref: '#/components/examples/simpleVaccineTimeline'
              schema:
                $ref: '#/components/schemas/vaccineCoverage'
          description: Status Ok
      summary: Get total global COVID-19 vaccine doses administered
   
  /v3/covid-19/vaccine/coverage/countries:
    get:
      parameters:
      - description: Number of days 
        in: query
        name: lastdays
        schema:
          default: 30
          type: string
      - description: simple or full.
        in: query
        name: fullData
        schema:
          default: 'false'
          type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                fullTimeline:
                  $ref: '#/components/examples/countriesFullVaccineTimeline'
                simpleTimeline:
                  $ref: '#/components/examples/countriesSimpleVaccineTimeline'
              schema:
                $ref: '#/components/schemas/vaccineCountriesCoverage'
          description: Status Ok
      summary: Get COVID-19 vaccine doses administered  
      tags:
      - 'COVID-19: Vaccine'
  /v3/covid-19/vaccine/coverage/countries/{country}:
    get:
      parameters:
      - description: country code
        in: path
        name: country
        required: true
        schema:
          type: string
      - description: Number of days 
        in: query
        name: lastdays
        schema:
          default: 30
          type: string
      - description: simple or full.
        in: query
        name: fullData
        schema:
          default: 'false'
          type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                fullTimeline:
                  $ref: '#/components/examples/countryFullVaccineTimeline'
                simpleTimeline:
                  $ref: '#/components/examples/countrySimpleVaccineTimeline'
              schema:
                $ref: '#/components/schemas/vaccineCountryCoverage'
          description: Status Ok
      summary: Get COVID-19 vaccine doses administered for a country 
      tags:
      - 'COVID-19: Vaccine'
  /v3/covid-19/vaccine/coverage/states:
    get:
      parameters:
      - description: Number of days 
        in: query
        name: lastdays
        schema:
          default: 30
          type: string
      - description: simple or full.
        in: query
        name: fullData
        schema:
          default: 'false'
          type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                fullTimeline:
                  $ref: '#/components/examples/statesFullVaccineTimeline'
                simpleTimeline:
                  $ref: '#/components/examples/statesSimpleVaccineTimeline'
              schema:
                $ref: '#/components/schemas/vaccineStatesCoverage'
          description: Status Ok
      summary: Get COVID-19 vaccine doses administered for all states
      tags:
      - 'COVID-19: Vaccine'
  /v3/covid-19/vaccine/coverage/states/{state}:
    get:
      parameters:
      - description: A valid state name
        in: path
        name: state
        required: true
        schema:
          type: string
      - description: Number of days 
        in: query
        name: lastdays
        schema:
          default: 30
          type: string
      - description: simple or full.
        in: query
        name: fullData
        schema:
          default: 'false'
          type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                fullTimeline:
                  $ref: '#/components/examples/stateFullVaccineTimeline'
                simpleTimeline:
                  $ref: '#/components/examples/stateSimpleVaccineTimeline'
              schema:
                $ref: '#/components/schemas/vaccineStateCoverage'
          description: Status Ok
      summary: Get COVID-19 vaccine doses administered for a state 
      tags:
      - 'COVID-19: Vaccine'
  /v3/covid-19/variants/countries/:
    get:
      description: Returns a list of supported country names
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/variantsECDC'
          description: Status Ok
      summary: Get a list of supported countries for ECDC specific data
      tags:
      - 'COVID-19: Variants'
  /v3/covid-19/variants/countries/{country}:
    get:
      parameters:
      - description: A valid country name 
          endpoint
        in: path
        name: country
        required: true
        schema:
          type: string
    
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/variantsCountriesECDC'
          description: Status Ok
      summary: Get COVID-19 ECDC reported data for a specific country
      tags:
      - 'COVID-19: Variants'
  


components:
  examples:
    countriesFullVaccineTimeline:
      summary: Full Vaccine Timeline
      value:
      - country: USA
        timeline:
        - daily: 1000
          dailyPerMillion: 1000
          date: 4/25/2021
          total: 1000
          totalPerHundred: 1000
    countriesSimpleVaccineTimeline:
      summary: Simple Vaccine Timeline
      value:
      - country: USA
        timeline:
          4/25/2021: 1000
    countryFullVaccineTimeline:
      summary: Full Vaccine Timeline
      value:
        country: USA
        timeline:
        - daily: 1000
          dailyPerMillion: 1000
          date: 4/25/2021
          total: 1000
          totalPerHundred: 1000
    countrySimpleVaccineTimeline:
      summary: Simple Vaccine Timeline
      value:
        country: USA
        timeline:
          4/25/2021: 1000
    fullVaccineTimeline:
      summary: Full Vaccine Timeline
      value:
      - daily: 1000
        dailyPerMillion: 1000
        date: 4/25/2021
        total: 1000
        totalPerHundred: 1000
    simpleVaccineTimeline:
      summary: Simple Vaccine Timeline
      value:
        4/25/2021: 1000
    stateFullVaccineTimeline:
      summary: Full Vaccine Timeline
      value:
        state: California
        timeline:
        - daily: 1000
          dailyPerMillion: 1000
          date: 4/25/2021
          total: 1000
          totalPerHundred: 1000
    stateSimpleVaccineTimeline:
      summary: Simple Vaccine Timeline
      value:
        state: California
        timeline:
          4/25/2021: 1000
    statesFullVaccineTimeline:
      summary: Full Vaccine Timeline
      value:
      - state: California
        timeline:
        - daily: 1000
          dailyPerMillion: 1000
          date: 4/25/2021
          total: 1000
          totalPerHundred: 1000
    statesSimpleVaccineTimeline:
      summary: Simple Vaccine Timeline
      value:
      - state: California
        timeline:
          4/25/2021: 1000
  schemas:
 
    covidAll:
      properties:
        active:
          type: number
        activePerOneMillion:
          type: number
        affectedCountries:
          type: number
        cases:
          type: number
        casesPerOneMillion:
          type: number
        critical:
          type: number
        criticalPerOneMillion:
          type: number
        deaths:
          type: number
        deathsPerOneMillion:
          type: number
        oneCasePerPeople:
          type: number
        oneDeathPerPeople:
          type: number
        oneTestPerPeople:
          type: number
        population:
          type: number
        recovered:
          type: number
        recoveredPerOneMillion:
          type: number
        tests:
          type: number
        testsPerOneMillion:
          type: number
        todayCases:
          type: number
        todayRecovered:
          type: number
        updated:
          type: number
   
    covidContinent:
      properties:
        active:
          type: number
        activePerOneMillion:
          type: number
        cases:
          type: number
        casesPerOneMillion:
          type: number
        continent:
          type: string
        continentInfo:
          properties:
            lat:
              type: number
            long:
              type: number
          type: object
        countries:
          items:
            type: string
          type: array
        critical:
          type: number
        criticalPerOneMillion:
          type: number
        deaths:
          type: number
        deathsPerOneMillion:
          type: number
        population:
          type: number
        recovered:
          type: number
        recoveredPerOneMillion:
          type: number
        tests:
          type: number
        testsPerOneMillion:
          type: number
        todayCases:
          type: number
        todayDeaths:
          type: number
        todayRecovered:
          type: number
        updated:
          type: number
    covidContinents:
      items:
        $ref: '#/components/schemas/covidContinent'
      type: array
    covidCountries:
      items:
        $ref: '#/components/schemas/covidCountry'
      type: array
    covidCountry:
      properties:
        active:
          type: number
        activePerOneMillion:
          type: number
        cases:
          type: number
        casesPerOneMillion:
          type: number
        continent:
          type: number
        country:
          type: string
        countryInfo:
          properties:
            _id:
              type: number
              uniqueItems: true
            flag:
              type: string
            iso2:
              type: string
              uniqueItems: true
            iso3:
              type: string
              uniqueItems: true
            lat:
              type: number
            long:
              type: number
          type: object
        critical:
          type: number
        criticalPerOneMillion:
          type: number
        deaths:
          type: number
        deathsPerOneMillion:
          type: number
        oneCasePerPeople:
          type: number
        oneDeathPerPeople:
          type: number
        oneTestPerPeople:
          type: number
        population:
          type: number
        recovered:
          type: number
        recoveredPerOneMillion:
          type: number
        tests:
          type: number
        testsPerOneMillion:
          type: number
        todayCases:
          type: number
        todayDeaths:
          type: number
        todayRecovered:
          type: number
        updated:
          type: number
    
    
  
    covidState:
      properties:
        active:
          type: number
        cases:
          type: number
        casesPerOneMillion:
          type: number
        deaths:
          type: number
        deathsPerOneMillion:
          type: number
        population:
          type: number
        state:
          type: string
        tests:
          type: number
        testsPerOneMillion:
          type: number
        todayCases:
          type: number
        todayDeaths:
          type: number
        updated:
          type: number
    covidStates:
      items:
        $ref: '#/components/schemas/covidState'
      type: array
    fullVaccineTimeline:
      items:
        properties:
          daily:
            type: number
          dailyPerMillion:
            type: number
          date:
            type: string
          total:
            type: number
          totalPerHundred:
            type: number
        type: object
      type: array

  
    phases:
      properties:
        candidates:
          type: string
        phase:
          type: string
    simpleVaccineTimeline:
      properties:
        date:
          type: number
      type: object
    
    vaccine:
      properties:
        candidate:
          type: string
        details:
          type: string
        institutions:
          items:
            type: string
          type: array
        mechanism:
          type: string
        sponsors:
          items:
            type: string
          type: array
        trialPhase:
          type: string
    vaccineCountriesCoverage:
      items:
        $ref: '#/components/schemas/vaccineCountryCoverage'
      type: array
    vaccineCountryCoverage:
      properties:
        country:
          type: string
        timeline:
          oneOf:
          - $ref: '#/components/schemas/simpleVaccineTimeline'
          - $ref: '#/components/schemas/fullVaccineTimeline'
      type: object
    vaccineCoverage:
      oneOf:
      - $ref: '#/components/schemas/simpleVaccineTimeline'
      - $ref: '#/components/schemas/fullVaccineTimeline'
    vaccineStateCoverage:
      properties:
        state:
          type: string
        timeline:
          oneOf:
          - $ref: '#/components/schemas/simpleVaccineTimeline'
          - $ref: '#/components/schemas/fullVaccineTimeline'
      type: object
    vaccineStatesCoverage:
      items:
        $ref: '#/components/schemas/vaccineStateCoverage'
      type: array
    vaccines:
      properties:
        data:
          items:
            $ref: '#/components/schemas/vaccine'
          type: array
        phases:
          items:
            $ref: '#/components/schemas/phases'
          type: array
        source:
          type: string
        totalCandidates:
          type: string
    variantsCountriesECDC:
      items:
        properties:
          country:
            type: string
          newCases:
            type: number
          numberDetectionsVariant:
            type: number
          numberSequenced:
            type: number
          numberSequencedKnownVariant:
            type: number
          percentSequenced:
            type: number
          percentVariant:
            type: number
          source:
            type: string
          updated:
            format: date
            type: number
          validDenominator:
            type: string
          variant:
            type: string
          yearWeek:
            type: string
        type: object
      type: array
    variantsECDC:
      items:
        type: string
      type: array